batch_size: 256
device: "cuda"
by_layer: true
override: true

huggingface:
  dataset_name: "tachyongun/MS_COCO_NSD_224x224_msi"
  model_ids: [
      "laion/CLIP-ViT-B-32-laion2B-s34B-b79K",
      #"laion/CLIP-ViT-bigG-14-laion2B-39B-b160k",
      #"laion/CLIP-ViT-H-14-laion2B-s32B-b79K",
      #"laion/CoCa-ViT-B-32-laion2B-s13B-b90k",
      #"laion/CoCa-ViT-L-14-laion2B-s13B-b90k",
    ]

data:
  large_data_path: ${oc.env:LARGE_DATA_PATH}
  nsd_directory: nsd
  dataset_cache_dir: ${oc.env:LARGE_DATA_PATH}/huggingface/datasets
  model_cache_dir: ${oc.env:LARGE_DATA_PATH}/huggingface/transformers
  output_dir: ${oc.env:LARGE_DATA_PATH}/nsd/image_embeddings
