batch_size: 256
device: "cuda"
by_layer: true
override: true

huggingface:
  dataset_name: "tachyongun/MS_COCO_NSD_224x224_msi"
  model_ids: ["helena-balabin/clip-graphormer_filtered_image_graphs"]

data:
  large_data_path: ${oc.env:LARGE_DATA_PATH}
  nsd_directory: nsd
  dataset_cache_dir: ${oc.env:LARGE_DATA_PATH}/huggingface/datasets
  model_cache_dir: ${oc.env:LARGE_DATA_PATH}/huggingface/transformers
  output_dir: ${oc.env:LARGE_DATA_PATH}/nsd/image_embeddings
