data:
  large_data_path: ${oc.env:LARGE_DATA_PATH}
  nsd_directory: nsd
  cache_dir: ${oc.env:LARGE_DATA_PATH}/huggingface/datasets
  data_format: func1pt8mm
  data_type: betas_fithrf_GLMdenoise_RR
  output_dir: ${oc.env:LARGE_DATA_PATH}/nsd/mvpa_decoder
  loading_n_jobs: 10
  use_cached_betas: true
  force_reload_cache: false
  betas_cache_dir: ${oc.env:LARGE_DATA_PATH}/nsd/cache

subjects:
  [
    "subj01",
    "subj02",
    "subj03",
    "subj04",
    "subj05",
    "subj06",
    "subj07",
    "subj08",
  ]
max_sessions: 40
random_state: 42
binarize_target: true
use_quartile_split: true
target_strategy: "zscore" # "zscore", "quartile", or "median"
zscore_threshold: 1.0

target_variables:
  [
    "image_graphs_n_nodes",
    "image_graphs_n_edges",
    "image_graphs_depth",
    "spatial_image_graphs_n_nodes",
    "spatial_image_graphs_n_edges",
    "spatial_image_graphs_depth",
    "action_image_graphs_n_nodes",
    "action_image_graphs_n_edges",
    "action_image_graphs_depth",
  ]

use_searchlight: true

classifier:
  backend: "torch_cuda"
  estimator: "ridge"
  scoring: "balanced_accuracy"
  cv: 3
  n_jobs: -1
  screening_percentile: 20 # Feature selection: top 20% by F-test

searchlight:
  radius: 6

# Better masking strategy
nsdgeneral_mask: true
snr_mask: false
snr_mask_threshold: 0.3
