data:
  large_data_path: ${oc.env:LARGE_DATA_PATH}
  nsd_directory: nsd
  cache_dir: ${oc.env:LARGE_DATA_PATH}/huggingface/datasets
  data_format: func1pt8mm
  data_type: betas_fithrf_GLMdenoise_RR
  output_dir: ${oc.env:LARGE_DATA_PATH}/nsd/mvpa_decoder
  loading_n_jobs: 10
  # Data caching settings
  use_cached_betas: true # Enable/disable beta caching
  force_reload_cache: false # Force regeneration of cached betas
  betas_cache_dir: ${oc.env:LARGE_DATA_PATH}/nsd/cache

subjects:
  [
    "subj03",
    "subj01",
    "subj02",
    "subj04",
    "subj05",
    "subj06",
    "subj07",
    "subj08",
  ]
max_sessions: 40
random_state: 42
binarize_target: false
target_variables:
  [
    "image_graphs_n_nodes",
    "image_graphs_n_edges",
    "image_graphs_depth",
    "spatial_image_graphs_n_nodes",
    "spatial_image_graphs_n_edges",
    "spatial_image_graphs_depth",
    "action_image_graphs_n_nodes",
    "action_image_graphs_n_edges",
    "action_image_graphs_depth",
  ]

use_searchlight: true

classifier:
  estimator: "ridge"
  scoring: "r2"
  cv: 3
  n_jobs: -1

searchlight:
  radius: 3

nsdgeneral_mask: false
snr_mask: true
snr_mask_threshold: 0.2
