data:
  large_data_path: ${oc.env:LARGE_DATA_PATH}
  nsd_directory: nsd
  dataset_cache_dir: ${oc.env:LARGE_DATA_PATH}/huggingface/datasets
  model_cache_dir: ${oc.env:LARGE_DATA_PATH}/huggingface/transformers
  data_format: func1pt8mm
  data_type: betas_fithrf_GLMdenoise_RR
  output_dir: ${oc.env:LARGE_DATA_PATH}/nsd/neural_encoder
  embedding_dir: ${oc.env:LARGE_DATA_PATH}/nsd/image_embeddings
  # Data caching settings
  use_cached_betas: true # Enable/disable beta caching
  force_reload_cache: false # Force regeneration of cached betas
  betas_cache_dir: ${oc.env:LARGE_DATA_PATH}/nsd/cache

by_layer: true
ridge_cv: false
cv: 5
random_state: 42

subjects: [
    "subj01",
    # "subj02",
    # "subj03",
    # "subj04",
    # "subj05",
    # "subj06",
    # "subj07",
    # "subj08",
  ]

model_ids: ["helena-balabin/clip-graphormer_filtered_image_graphs"]

max_sessions: 40
nsdgeneral_mask: true
