data:
  input_dir: ${oc.env:LARGE_DATA_PATH}/nsd/mvpa_decoder
  output_dir: ${oc.env:LARGE_DATA_PATH}/nsd/mvpa_decoder
  nsd_directory: ${oc.env:LARGE_DATA_PATH}/nsd
  fs_directory: ${oc.env:LARGE_DATA_PATH}/nsd/freesurfer

visualization:
  colormap: "cold_hot"
  threshold: 0.5
  engine: "plotly"

mapping:
  space_from: "func1pt8"
  space_to: "MNI"
  betas_type: "betas_fithrf_GLMdenoise_RR"

target_variables:
  [
    "image_graphs_n_edges",
    "image_graphs_n_nodes",
    "image_graphs_depth",
    "spatial_image_graphs_n_edges",
    "spatial_image_graphs_depth",
    "spatial_image_graphs_n_nodes",
    "action_image_graphs_n_edges",
    "action_image_graphs_depth",
    "action_image_graphs_n_nodes",
  ]
