data:
    input_dir: ${oc.env:LARGE_DATA_PATH}/nsd/mvpa_decoder
    output_dir: ${oc.env:LARGE_DATA_PATH}/nsd/mvpa_decoder
    nsd_directory: ${oc.env:LARGE_DATA_PATH}/nsd
    fs_directory: ${oc.env:LARGE_DATA_PATH}/nsd/freesurfer

visualization:
    colormap: "cold_hot"
    threshold: 0.0001

mapping:
    space_from: "func1pt8"
    space_to: "fsaverage"
    betas_type: "betas_fithrf_GLMdenoise_RR"
