data:
  results_csv: ${oc.env:LARGE_DATA_PATH}/nsd/mvpa_decoder/mvpa_decoder_results.csv
  output_dir: ${oc.env:LARGE_DATA_PATH}/nsd/mvpa_decoder
scoring: "accuracy"
target_variables:
  [
    "image_graphs_n_nodes",
    "image_graphs_n_edges",
    "image_graphs_depth",
    "spatial_image_graphs_n_nodes",
    "spatial_image_graphs_n_edges",
    "spatial_image_graphs_depth",
    "action_image_graphs_n_nodes",
    "action_image_graphs_n_edges",
    "action_image_graphs_depth",
  ]
