name: Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        name: Code Quality
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.12"]
                tox-command: ["manifest", "lint", "pyroma", "mypy"]
        steps:
            - uses: actions/checkout@v4
            - name: "Install uv"
              uses: "astral-sh/setup-uv@v3"
              with:
                  enable-cache: true
                  cache-dependency-glob: "pyproject.toml"
            - name: "Run command"
              run: |
                  uvx -p ${{ matrix.python-version }} --with tox-uv tox -e ${{ matrix.tox-command }}
